name: Build and Publish Docker Image

on:
  push:
    branches:  main

  release:
    types: [ published ]
  workflow_dispatch:

env:
  REGISTRY: docker.io
  IMAGE_NAME: zakari007/hextris

jobs:
  docker-build-test:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          tags: hextris:pr-${{ github.event.number }}

      - name: Test Docker image
        run: |
          docker run -d --name hextris-test hextris:pr-${{ github.event.number }}
          sleep 10
          
          # Test if container is running
          if docker ps | grep hextris-test; then
            echo "✅ Container is running"
          else
            echo "❌ Container failed to start"
            docker logs hextris-test
            exit 1
          fi
          
          # Cleanup
          docker stop hextris-test
          docker rm hextris-test

  docker-build-push:
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/hextris
          tags: |
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master' }}
            type=sha,prefix=,suffix=
            type=ref,event=branch
            type=ref,event=tag
            type=semver,pattern={{version}}

      - name: Build image (load for testing)
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          load: true
          tags: test-hextris:latest

      - name: Run container
        run: |
          docker run -d --name hextris -p 8080:80 test-hextris:latest
          sleep 5



 

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}