name: Build, Test, and Publish Hextris Docker image

on:
  push:
    branches: 
        - main
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: docker.io/${{ secrets.DOCKER_USERNAME }}/hextris
          tags: |
            type=sha
            type=ref,event=branch
            type=ref,event=tag
            type=semver,pattern={{version}}

      - name: Build image (load for testing)
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          load: true
          tags: test-hextris:latest

      - name: Run container
        run: |
          docker run -d --name hextris -p 8080:80 test-hextris:latest
          sleep 5

      - name: Test Hextris index.html title
        run: |
          TITLE=$(curl --silent http://localhost:8080/index.html | grep -oP '(?<=<title>).*?(?=</title>)')
          echo "Page title: $TITLE"
          if [ "$TITLE" != "Hextris" ]; then
            echo "Hextris test failed: title is not 'Hextris'"
            exit 1
          fi

      - name: Stop container
        if: always()
        run: docker rm -f hextris

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}